//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Shop_OrderForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Shop_OrderForm()
        {
            this.T_Shop_OFProduct = new HashSet<T_Shop_OFProduct>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> WuliuId { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FahuoId { get; set; }
    
        public virtual T_Shop_Users T_Shop_Users { get; set; }
        public virtual T_Shop_Wuliu T_Shop_Wuliu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Shop_OFProduct> T_Shop_OFProduct { get; set; }
    }
}
