//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Shop_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Shop_Product()
        {
            this.T_Shop_Basket = new HashSet<T_Shop_Basket>();
            this.T_Shop_OFProduct = new HashSet<T_Shop_OFProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Store { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Pic { get; set; }
    
        public virtual T_Shop_ProductCategory T_Shop_ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Shop_Basket> T_Shop_Basket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Shop_OFProduct> T_Shop_OFProduct { get; set; }
    }
}
